"""Remove auto tag enabled from settings

Revision ID: 1fa2d369153d
Revises: c3a4f93e21aa
Create Date: 2026-04-29 14:19:47.704254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa2d369153d'
down_revision: Union[str, None] = 'c3a4f93e21aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('auto_tag_enabled')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_tag_enabled', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
