"""add emby support and emby_season_id to seasons

Revision ID: 20666951d75d
Revises: 1b25d7fd62d3
Create Date: 2026-04-17 19:08:29.263765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20666951d75d'
down_revision: Union[str, None] = '1b25d7fd62d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emby_season_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('emby_season_id')

    # ### end Alembic commands ###
