"""Remove auto tag suffix settings

Revision ID: 84e8889cda26
Revises: 1fa2d369153d
Create Date: 2026-04-29 14:36:56.058996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e8889cda26'
down_revision: Union[str, None] = '1fa2d369153d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('cleanup_tag_suffix')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleanup_tag_suffix', sa.VARCHAR(length=15), nullable=False))

    # ### end Alembic commands ###
