"""Add extra_settings to ServiceConfig

Revision ID: 9930cd1a58b8
Revises: a3f1c8e92b47
Create Date: 2026-04-21 18:21:50.022405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9930cd1a58b8'
down_revision: Union[str, None] = 'a3f1c8e92b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_settings', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_configs', schema=None) as batch_op:
        batch_op.drop_column('extra_settings')

    # ### end Alembic commands ###
