"""
Build script for the Reclaimerr desktop app. Supports Windows, macOS, and Linux.

Usage (from repo root):
    uv run python scripts/build_desktop.py

Output (onedir mode):
    Windows : dist/Reclaimerr/Reclaimerr.exe
    macOS   : dist/Reclaimerr/Reclaimerr
    Linux   : dist/Reclaimerr/Reclaimerr

User data (DB, logs, avatars) is stored in the platform data dir at runtime
(%%LOCALAPPDATA%%/reclaimerr on Windows, ~/Library/Application Support/reclaimerr
on macOS, ~/.local/share/reclaimerr on Linux).
"""

import platform
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FRONTEND_DIR = REPO_ROOT / "frontend"
FRONTEND_DIST = FRONTEND_DIR / "dist"
DESKTOP_DIR = REPO_ROOT / "desktop"
OUTPUT_NAME = "reclaimerr"
SPEC_FILE = REPO_ROOT / f"{OUTPUT_NAME}.spec"

PLATFORM = platform.system()
if PLATFORM == "Windows":
    EXE_SUFFIX = ".exe"
    ICON: Path | None = FRONTEND_DIR / "static" / "favicon.ico"
    USE_UPX = True
elif PLATFORM == "Darwin":
    EXE_SUFFIX = ""
    ICON = None  # macOS needs .icns; skip until we have one
    USE_UPX = False
else:  # linux
    EXE_SUFFIX = ""
    ICON = None  # ignored on Linux
    USE_UPX = False


def run(cmd: list[str], **kwargs):
    print(f"\n>>> {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, **kwargs)
    if result.returncode != 0:
        sys.exit(result.returncode)


def build_frontend():
    print("\n=== Building frontend ===")
    run(["npm", "run", "build"], cwd=FRONTEND_DIR, shell=True)
    if not FRONTEND_DIST.exists():
        print("ERROR: frontend/dist not found after build")
        sys.exit(1)


def write_spec() -> None:
    """Generate the PyInstaller .spec file.

    A spec file is the idiomatic way to configure PyInstaller for non-trivial
    apps - keeps all packaging logic in one readable place instead of a huge
    CLI invocation.
    """
    # Paths must use forward slashes inside the spec (it's evaluated as Python
    # on any platform, but PyInstaller on Windows also accepts them fine).
    frontend_dist = FRONTEND_DIST.as_posix()
    icon_dir = (FRONTEND_DIR / "static").as_posix()
    icon_line = f'    icon="{ICON.as_posix()}",' if ICON else ""
    upx = USE_UPX
    entry = (DESKTOP_DIR / "__main__.py").as_posix()

    # cspell:disable
    spec = f"""\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by scripts/build_desktop.py - do not edit by hand.

from PyInstaller.utils.hooks import collect_all

datas = []
binaries = []
hiddenimports = []

# ------------------------------------------------------------------
# Collect packages whose submodules/data can't be found by static
# analysis alone (plugin registries, data files shipped alongside .py).
# collect_all() returns (datas, binaries, hiddenimports) tuples.
# ------------------------------------------------------------------
for pkg in (
    "backend",   # our app - entry point is a string in uvicorn.Config
    "desktop",   # tray / server helpers
    "uvicorn",   # ships non-.py data files
):
    d, b, h = collect_all(pkg)
    datas    += d
    binaries += b
    hiddenimports += h

# Built frontend SPA and tray icon are not Python packages - add manually.
datas += [
    ("{frontend_dist}", "frontend/dist"),
    ("{icon_dir}",      "frontend/static"),
]

# Runtime-only imports that static analysis can never see:
#   anyio  - picks asyncio vs trio backend via a registry at runtime
#   aiosqlite + its SQLAlchemy dialect - referenced only as a URL string
#     ("sqlite+aiosqlite:///..."), never as a Python import
hiddenimports += [
    "anyio._backends._asyncio",
    "aiosqlite",
    "sqlalchemy.dialects.sqlite.aiosqlite",
]

a = Analysis(
    ["{entry}"],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="{OUTPUT_NAME}",
{icon_line}
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx={upx},
    console=False,   # no console window - we're a tray app
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx={upx},
    upx_exclude=[],
    name="{OUTPUT_NAME}",
)
"""
    # cspell:enable
    SPEC_FILE.write_text(spec)
    print(f"\n=== Wrote {SPEC_FILE.name} ===")


def build_exe():
    print("\n=== Running PyInstaller ===")
    run(
        [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", str(SPEC_FILE)],
        cwd=REPO_ROOT,
    )


def verify():
    exe = REPO_ROOT / "dist" / OUTPUT_NAME / f"{OUTPUT_NAME}{EXE_SUFFIX}"
    if exe.exists():
        print(f"\nBuild succeeded: {exe}")
    else:
        print(f"\nBuild failed - executable not found at expected path: {exe}")
        sys.exit(1)


if __name__ == "__main__":
    build_frontend()
    write_spec()
    build_exe()
    verify()
