from __future__ import annotations

import asyncio
import os
import secrets
import sys
from pathlib import Path

import uvicorn
from platformdirs import user_data_dir

from desktop.utils import is_bundled

APP_NAME = "Reclaimerr"
_SECRETS_FILE = "secrets.env"
_SECRET_LEN = 64  # characters (hex)


class ReclaimerServer:
    """Encapsulates the uvicorn server and related environment setup for the Reclaimerr desktop app."""

    __slots__ = ("port", "_server")

    def __init__(self, port: int = 7474) -> None:
        self.port = port
        self._server: uvicorn.Server | None = None

    #### path helpers
    @property
    def app_dir(self) -> Path:
        """Repo root in dev (directory containing the .exe when bundled)."""
        if is_bundled:
            return Path(sys.executable).parent
        return Path(__file__).resolve().parent.parent

    @property
    def data_dir(self) -> Path:
        """
        User-writable data directory.
        - Bundled: %LOCALAPPDATA%/Reclaimerr  (via platformdirs)
        - Dev:     <repo_root>/data
        """
        if is_bundled:
            return Path(user_data_dir(APP_NAME, appauthor=False))
        return self.app_dir / "data"

    #### lifecycle
    def _ensure_secrets(self) -> None:
        """
        Load (or generate on first run) JWT secret and encryption key.

        Secrets are stored in data_dir/secrets.env so they survive restarts.
        Using a dedicated file (separate from .env) means user editable config
        and auto generated secrets never collide.
        """
        secrets_path = self.data_dir / _SECRETS_FILE
        self.data_dir.mkdir(parents=True, exist_ok=True)

        if secrets_path.exists():
            # parse the simple KEY=VALUE file ourselves without any extra deps.
            for line in secrets_path.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    os.environ.setdefault(k.strip(), v.strip())
        else:
            jwt_secret = secrets.token_hex(_SECRET_LEN // 2)
            enc_key = secrets.token_hex(_SECRET_LEN // 2)
            secrets_path.write_text(
                "# Auto generated by Reclaimerr on first launch. Do not share.\n"
                f"JWT_SECRET={jwt_secret}\n"
                f"ENCRYPTION_KEY={enc_key}\n"
            )
            os.environ["JWT_SECRET"] = jwt_secret
            os.environ["ENCRYPTION_KEY"] = enc_key

    def prepare_env(self) -> None:
        """
        Set environment variables before any backend module is imported.
        Must be called once from the main thread before serve().
        """
        os.environ["DATA_DIR"] = str(self.data_dir)
        os.environ["STATIC_DIR"] = str(self.data_dir / "static")
        os.environ["AVATARS_DIR"] = str(self.data_dir / "static" / "avatars")
        # Bundled read  only assets (frontend SPA) are extracted by PyInstaller
        # into _MEIPASS (_internal/), NOT into the exe's parent directory.
        # is_bundled IS the _MEIPASS path, so use it directly when frozen.
        frontend_root = is_bundled if is_bundled else self.app_dir
        os.environ["FRONTEND_DIST"] = str(frontend_root / "frontend" / "dist")
        os.environ["API_PORT"] = str(self.port)

        if is_bundled:
            # FROZEN: no .env present (auto generate secrets on first run and
            # persist them so they survive restarts).
            self._ensure_secrets()
        # DEV: the repo root .env is picked up by pydantic settings automatically to keep things simple.

    def serve(self) -> None:
        """
        Block the calling thread on the uvicorn server.
        Must be called from the **main thread** so asyncio owns it.
        Returns only after stop() is called.
        """
        # This must be imported here (not at module level) so that prepare_env() has already
        # set DATA_DIR / FRONTEND_DIST / etc. before Settings() is instantiated.
        from backend.api.main import app

        config = uvicorn.Config(
            app,
            host="127.0.0.1",
            port=self.port,
            loop="asyncio",
            log_config=None,  # backend has its own logger
        )
        self._server = uvicorn.Server(config)
        asyncio.run(self._server.serve())

    def stop(self) -> None:
        """Request a graceful uvicorn shutdown. Safe to call from any thread."""
        if self._server:
            self._server.should_exit = True
