from __future__ import annotations

import asyncio
import os
import secrets
import sys
from pathlib import Path

import uvicorn
from platformdirs import user_data_dir

from desktop.utils import find_free_port, is_bundled, read_env_file

APP_NAME = "Reclaimerr"
_SECRETS_FILE = "secrets.env"
_SECRET_LEN = 64  # characters (hex)


class ReclaimerServer:
    """Encapsulates the uvicorn server and related environment setup for the Reclaimerr desktop app."""

    __slots__ = ("api_host", "port", "cors_origin", "_server")

    def __init__(self) -> None:
        self.api_host = "127.0.0.1"
        self.port = 8000
        self.cors_origin = "http://localhost:3000"
        self._load_env_vars()

        self._server: uvicorn.Server | None = None

    def _load_env_vars(self) -> None:
        """Load environment variables from a .env file in the bundle (if it exists)."""
        # if not bundled (= running in dev), do nothing and rely on pydantic settings to
        # load from the repo root .env automatically.
        if is_bundled is None:
            return

        # if bundled, look for a .env in the bundle (same location as the .exe) and load any env vars from it.
        env_path = is_bundled.parent / ".env"
        if not env_path.exists():
            return
        env_vars = read_env_file(env_path)

        # override default settings with any values from the .env (supports user override in production).
        self.api_host = env_vars.get("API_HOST", self.api_host)
        self.port = int(env_vars.get("API_PORT", self.port))
        self.cors_origin = env_vars.get("CORS_ORIGIN", self.cors_origin)

        # forward ADMIN_PASSWORD if present so the backend can reset the admin password on startup if needed.
        if "ADMIN_PASSWORD" in env_vars:
            os.environ["ADMIN_PASSWORD"] = env_vars["ADMIN_PASSWORD"]

    #### path helpers
    @property
    def app_dir(self) -> Path:
        """Repo root in dev (directory containing the .exe when bundled)."""
        if is_bundled:
            return Path(sys.executable).parent
        return Path(__file__).resolve().parent.parent

    @property
    def data_dir(self) -> Path:
        """
        User-writable data directory.
        - Bundled: %LOCALAPPDATA%/Reclaimerr  (via platformdirs)
        - Dev:     <repo_root>/data
        """
        if is_bundled:
            return Path(user_data_dir(APP_NAME, appauthor=False))
        return self.app_dir / "data"

    #### lifecycle
    def prepare_env(self) -> None:
        """
        Set environment variables before any backend module is imported.
        Must be called once from the main thread before serve().
        """
        os.environ["DATA_DIR"] = str(self.data_dir)
        os.environ["STATIC_DIR"] = str(self.data_dir / "static")
        os.environ["AVATARS_DIR"] = str(self.data_dir / "static" / "avatars")
        # Bundled read  only assets (frontend SPA) are extracted by PyInstaller
        # into _MEIPASS (_internal/), NOT into the exe's parent directory.
        # is_bundled IS the _MEIPASS path, so use it directly when frozen.
        frontend_root = is_bundled if is_bundled else self.app_dir
        os.environ["FRONTEND_DIST"] = str(frontend_root / "frontend" / "dist")
        os.environ["API_PORT"] = str(self.port)
        os.environ["CORS_ORIGINS"] = self.cors_origin

        if is_bundled:
            # FROZEN: no .env present (auto generate secrets on first run and
            # persist them so they survive restarts).
            self._ensure_secrets()
        # DEV: the repo root .env is picked up by pydantic settings automatically to keep things simple.

    def _ensure_secrets(self) -> None:
        """
        Load (or generate on first run) JWT secret and encryption key.

        Secrets are stored in data_dir/secrets.env so they survive restarts.
        Using a dedicated file (separate from .env) means user editable config
        and auto generated secrets never collide.
        """
        secrets_path = self.data_dir / _SECRETS_FILE
        self.data_dir.mkdir(parents=True, exist_ok=True)

        if secrets_path.exists():
            secrets_vars = read_env_file(secrets_path)
            os.environ.update(secrets_vars)
        else:
            jwt_secret = secrets.token_hex(_SECRET_LEN // 2)
            enc_key = secrets.token_hex(_SECRET_LEN // 2)
            secrets_path.write_text(
                "# Auto generated by Reclaimerr on first launch. Do not share.\n"
                f"JWT_SECRET={jwt_secret}\n"
                f"ENCRYPTION_KEY={enc_key}\n"
            )
            os.environ["JWT_SECRET"] = jwt_secret
            os.environ["ENCRYPTION_KEY"] = enc_key

    def serve(self) -> None:
        """
        Block the calling thread on the uvicorn server.
        Must be called from the **main thread** so asyncio owns it.
        Returns only after stop() is called.
        """
        # This must be imported here (not at module level) so that prepare_env() has already
        # set DATA_DIR / FRONTEND_DIST / etc. before Settings() is instantiated.
        from backend.api.main import app

        self.port = find_free_port(self.api_host, self.port)
        # keep settings in sync in case it was changed by _find_free_port
        os.environ["API_PORT"] = str(self.port)

        config = uvicorn.Config(
            app,
            host=self.api_host,
            port=self.port,
            loop="asyncio",
            log_config=None,  # backend has its own logger
        )
        self._server = uvicorn.Server(config)
        asyncio.run(self._server.serve())

    def stop(self) -> None:
        """Request a graceful uvicorn shutdown. Safe to call from any thread."""
        if self._server:
            self._server.should_exit = True
